# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0002_auto_20170811_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pathtopicture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
