# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0005_dairyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
    ]
