# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiteat', '0006_product_calories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DairyEntry',
            new_name='DiaryEntry',
        ),
    ]
